# This workflow will build, test, and lint the Express.go framework
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Express.go CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Verify compilation
        # This step will not generate binary files, only checking if the code can be compiled
        run: go build -v ./...

      - name: Verify examples
        # Ensure example applications can be compiled correctly
        run: |
          if [ -d "cmd/examples" ]; then
            for dir in cmd/examples/*/; do
              if [ -d "$dir" ]; then
                echo "Verifying example: $dir"
                (cd "$dir" && go build -v)
              fi
            done
          fi
